myshop/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
]

shop/urls.py
from django.urls import path,re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

app_name = 'shop'

urlpatterns = [
    path('search/', views.search, name='search'),
    path('market', views.market, name='market'),
    path('store', views.product2_list, name='product2_list'),
    path('add1', views.add1, name='add1'),
    path('', views.index, name='index'),
    path('xxx', views.xxx, name='xxx'),
    path('1', views.m1, name='1'),
    path('2', views.m2, name='2'),
    path('3', views.m3, name='3'),
    path('4', views.m4, name='4'),
    path('5', views.m5, name='5'),
    path('6', views.m6, name='6'),
    path('7', views.m7, name='7'),
    path('8', views.m8, name='8'),
    path('9', views.m9, name='9'),
    path('10', views.m10, name='10'),
    path('shop', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('d/<int:id>/<slug:slug>/', views.product2_detail, name='product2_detail'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse

class user(models.Model):
    username = models.CharField(max_length = 50,verbose_name='用户名')
    password = models.CharField(max_length = 50,verbose_name='密码')
    gender = models.CharField(max_length=10, choices=(('M','男'),('F','女')), default='男', verbose_name='性别')
    phonenumber = models.CharField(max_length=50,verbose_name='电话号码')
    email = models.CharField(max_length=50,verbose_name='邮箱')
    #img = models.ImageField(upload_to='photos',height_field='height', width_field='width',default='static/no_image.png',verbose_name='头像')
    signature = models.CharField(max_length=200,verbose_name='个人签名')
    
    def __str__(self):
        return self.username
    
class market(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    activityTXT = models.CharField(max_length=200,verbose_name='活动信息')
    countTXT = models.CharField(max_length=200,verbose_name='折扣信息')
    image = models.ImageField(upload_to='markett', blank=True)
    score = models.DecimalField(max_digits=10, decimal_places=2)
    addressTXT = models.CharField(max_length=200,verbose_name='地址')
    description = models.TextField(blank=True)
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'market'
        verbose_name_plural = 'markets'

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_list_by_market',args=[self.slug])
    
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',args=[self.slug])


class Product(models.Model):
    market = models.ForeignKey(market, related_name='market', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='category', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.DecimalField(max_digits=10, decimal_places=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_detail',args=[self.id,self.slug])
    def get_absolute_url2(self):
        return reverse('shop:product2_detail',args=[self.id,self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.contrib.auth.decorators import login_required

@login_required
def search(request):
    q = request.GET.get('q')
    error_msg = ''
    category = None
    categories = Category.objects.all()

    if not q:
        error_msg = '请输入关键词'
        return render(request, 'shop/result.html', {'error_msg': error_msg})

    product_list_search = Product.objects.filter(name__icontains=q)
    return render(request, 'shop/result.html', {'error_msg': error_msg,
                                               'category': category, 'categories': categories,'product_list_search': product_list_search})
@login_required
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(categories, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html',
                  {'category': category, 'categories': categories, 'products': products})

@login_required
def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    return render(request, 'shop/product/detail.html', {'product': product})

@login_required
def index(request):
    return render(request, 'shop/index.html')

@login_required
def xxx(request):
    return render(request, 'shop/xxx.html')
def m1(request):
    return render(request, 'shop/1.html')
def m2(request):
    return render(request, 'shop/2.html')
def m3(request):
    return render(request, 'shop/3.html')
def m4(request):
    return render(request, 'shop/4.html')
def m5(request):
    return render(request, 'shop/5.html')
def m6(request):
    return render(request, 'shop/6.html')
def m7(request):
    return render(request, 'shop/7.html')
def m8(request):
    return render(request, 'shop/8.html')
def m9(request):
    return render(request, 'shop/9.html')
def m10(request):
    return render(request, 'shop/10.html')
def market(request):
    return render(request,'shop/market.html')
def add1(request):
    return render(request,'shop/add1.html')

@login_required
def product2_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(categories, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list2.html',
                  {'category': category, 'categories': categories, 'products': products})

@login_required
def product2_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    return render(request, 'shop/product/detail2.html', {'product': product})

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {{ product.name }}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <h2>{{ product.name }}</h2>
        <h3><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h3>
                <hr>
        <img style="width:300px;"src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <p class="price">${{ product.price }}</p>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

shop/templates/shop/product/detail2.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {{ product.name }}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <h2>{{ product.name }}</h2>
        <h3><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h3>
                <hr>
        <img style="width:300px;"src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <p class="price">${{ product.price }}</p>
        {{ product.stock }}
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
        {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<div id="header-search-box">
        <form role="search" method="get" id="searchform" action="{% url 'shop:search' %}">
          {% csrf_token %}
          <input type="search" name="q" placeholder="Search" required>
          <button type="submit"><span class="ion-ios-search-strong"></span>搜索</button>
        </form>
      </div>
    </form>
        <div id="sidebar">
            <h3 >Categories</h3>
            <ul>
                <li {% if not category %}class="selected"{% endif %}>
                    <a href="{% url "shop:product_list" %}">All</a>
                </li>
                {% for c in categories %}
                    <li {% if category.slug == c.slug %}class="selected"
                        {% endif %}>
                        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div id="main" class="product-list">
            <h2 >{% if category %}{{ category.name }}{% else %}Products
            {% endif %}</h2>
            {% for product in products %}
                <div class="item">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="
                                {% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                    </a>
                     <br>
                    <a id="proName" href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                    <br>
                    ${{ product.price }}
                </div>
            {% endfor %}
        </div><br>
{% endblock %}

shop/templates/shop/product/list2.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
        {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
        <div id="sidebar">
            <h3 style="margin-left: 10%;">Categories</h3>
            <ul>
                <li {% if not category %}class="selected"{% endif %}>
                    <a href="{% url "shop:product2_list" %}">All</a>
                </li>
                {% for c in categories %}
                    <li {% if category.slug == c.slug %}class="selected"
                        {% endif %}>
                        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                {% endfor %}
                <li>
                    <a href="{% url "shop:add1" %}">添加商品</a>
                </li>
            </ul>
        </div>
        <div id="main" class="product-list" style="margin-left:10%;">
            <h2 >{% if category %}{{ category.name }}{% else %}Products
            {% endif %}</h2>
            {% for product in products %}
                <div class="item">
                    <a href="{{ product.get_absolute_url2 }}">
                        <img src="
                                {% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                    </a>
                     <br>
                    <a id="proName" href="{{ product.get_absolute_url2 }}">{{ product.name }}</a>
                    <br>
                    ${{ product.price }}
                </div>
            {% endfor %}
        </div><br>
{% endblock %}