myshop/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
]

shop/urls.py
from django.urls import path,re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

app_name = 'shop'

urlpatterns = [
    path('search/', views.search, name='search'),
    path('market', views.market, name='market'),
    path('store', views.product2_list, name='product2_list'),
    path('add1', views.add1, name='add1'),
    path('', views.index, name='index'),
    path('xxx', views.xxx, name='xxx'),
    path('1', views.m1, name='1'),
    path('2', views.m2, name='2'),
    path('3', views.m3, name='3'),
    path('4', views.m4, name='4'),
    path('5', views.m5, name='5'),
    path('6', views.m6, name='6'),
    path('7', views.m7, name='7'),
    path('8', views.m8, name='8'),
    path('9', views.m9, name='9'),
    path('10', views.m10, name='10'),
    path('shop', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('d/<int:id>/<slug:slug>/', views.product2_detail, name='product2_detail'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse

class user(models.Model):
    username = models.CharField(max_length = 50,verbose_name='用户名')
    password = models.CharField(max_length = 50,verbose_name='密码')
    gender = models.CharField(max_length=10, choices=(('M','男'),('F','女')), default='男', verbose_name='性别')
    phonenumber = models.CharField(max_length=50,verbose_name='电话号码')
    email = models.CharField(max_length=50,verbose_name='邮箱')
    #img = models.ImageField(upload_to='photos',height_field='height', width_field='width',default='static/no_image.png',verbose_name='头像')
    signature = models.CharField(max_length=200,verbose_name='个人签名')
    
    def __str__(self):
        return self.username
    
class market(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    activityTXT = models.CharField(max_length=200,verbose_name='活动信息')
    countTXT = models.CharField(max_length=200,verbose_name='折扣信息')
    image = models.ImageField(upload_to='markett', blank=True)
    score = models.DecimalField(max_digits=10, decimal_places=2)
    addressTXT = models.CharField(max_length=200,verbose_name='地址')
    description = models.TextField(blank=True)
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'market'
        verbose_name_plural = 'markets'

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_list_by_market',args=[self.slug])
    
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',args=[self.slug])


class Product(models.Model):
    market = models.ForeignKey(market, related_name='market', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='category', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.DecimalField(max_digits=10, decimal_places=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_detail',args=[self.id,self.slug])
    def get_absolute_url2(self):
        return reverse('shop:product2_detail',args=[self.id,self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.contrib.auth.decorators import login_required

@login_required
def search(request):
    q = request.GET.get('q')
    error_msg = ''
    category = None
    categories = Category.objects.all()

    if not q:
        error_msg = '请输入关键词'
        return render(request, 'shop/result.html', {'error_msg': error_msg})

    product_list_search = Product.objects.filter(name__icontains=q)
    return render(request, 'shop/result.html', {'error_msg': error_msg,
                                               'category': category, 'categories': categories,'product_list_search': product_list_search})
@login_required
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(categories, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html',
                  {'category': category, 'categories': categories, 'products': products})

@login_required
def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    return render(request, 'shop/product/detail.html', {'product': product})

@login_required
def index(request):
    return render(request, 'shop/index.html')

@login_required
def xxx(request):
    return render(request, 'shop/xxx.html')
def m1(request):
    return render(request, 'shop/1.html')
def m2(request):
    return render(request, 'shop/2.html')
def m3(request):
    return render(request, 'shop/3.html')
def m4(request):
    return render(request, 'shop/4.html')
def m5(request):
    return render(request, 'shop/5.html')
def m6(request):
    return render(request, 'shop/6.html')
def m7(request):
    return render(request, 'shop/7.html')
def m8(request):
    return render(request, 'shop/8.html')
def m9(request):
    return render(request, 'shop/9.html')
def m10(request):
    return render(request, 'shop/10.html')
def market(request):
    return render(request,'shop/market.html')
def add1(request):
    return render(request,'shop/add1.html')

@login_required
def product2_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(categories, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list2.html',
                  {'category': category, 'categories': categories, 'products': products})

@login_required
def product2_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    return render(request, 'shop/product/detail2.html', {'product': product})

shop/templates/shop/1.html
<link rel="stylesheet" href="/static/reg.css" />
<!DOCTYPE html>
<html>
<head>
    <meta  charset="utf-8">
	<title></title>
<body>
    <h1>联华超市（杭州大华店）路线<input type="button" class="a1" value="返回" onclick="javascript:history.back();"></h1>
    <table><tr>
        <td><img src="media/img/m1.jpg" border=0></td>
        <td><img src="media/img/1x.jpg" border=0></td>
    </tr></table>
    
</body>
</html>

shop/templates/shop/10.html
<link rel="stylesheet" href="/static/reg.css" />
<!DOCTYPE html>
<html>
<head>
    <meta  charset="utf-8">
	<title></title>
<body>
    <h1>如海仓前购物中心 路线<input type="button" class="a1" value="返回" onclick="javascript:history.back();"></h1>
    <table><tr>
        <td><img src="media/img/m10.jpg" border=0></td>
        <td><img src="media/img/10x.jpg" border=0></td>
    </tr></table>
</body>
</html>

shop/templates/shop/2.html
<link rel="stylesheet" href="/static/reg.css" />
<!DOCTYPE html>
<html>
<head>
    <meta  charset="utf-8">
	<title></title>
<body>
    <h1>乐时城路线<input type="button" class="a1" value="返回" onclick="javascript:history.back();"></h1>
    <table><tr>
        <td><img src="media/img/m2.jpg" border=0></td>
        <td><img src="media/img/2x.jpg" border=0></td>
    </tr></table>
</body>
</html>

shop/templates/shop/3.html
<link rel="stylesheet" href="/static/reg.css" />
<!DOCTYPE html>
<html>
<head>
    <meta  charset="utf-8">
	<title></title>
<body>
    <h1>世纪华联（永福店）路线<input type="button" class="a1" value="返回" onclick="javascript:history.back();"></h1>
    <table><tr>
        <td><img src="media/img/m3.jpg" border=0></td>
        <td><img src="media/img/3x.jpg" border=0></td>
    </tr></table>
</body>
</html>

shop/templates/shop/4.html
<link rel="stylesheet" href="/static/reg.css" />
<!DOCTYPE html>
<html>
<head>
    <meta  charset="utf-8">
	<title></title>
<body>
    <h1>通城好又多购物（梦想小镇店）路线<input type="button" class="a1" value="返回" onclick="javascript:history.back();"></h1>
    <table><tr>
        <td><img src="media/img/m4.jpg" border=0></td>
        <td><img src="media/img/4x.jpg" border=0></td>
    </tr></table>
</body>
</html>

shop/templates/shop/5.html
<link rel="stylesheet" href="/static/reg.css" />
<!DOCTYPE html>
<html>
<head>
    <meta  charset="utf-8">
	<title></title>
<body>
    <h1>好又多超市（五常永福店）<input type="button" class="a1" value="返回" onclick="javascript:history.back();"></h1>
    <table><tr>
        <td><img src="media/img/m5.jpg" border=0></td>
        <td><img src="media/img/5x.jpg" border=0></td>
    </tr></table>
</body>
</html>

shop/templates/shop/6.html
<link rel="stylesheet" href="/static/reg.css" />
<!DOCTYPE html>
<html>
<head>
    <meta  charset="utf-8">
	<title></title>
<body>
    <h1>华联超市（仓前店）路线<input type="button" class="a1" value="返回" onclick="javascript:history.back();"></h1>
    <table><tr>
        <td><img src="media/img/m6.jpg" border=0></td>
        <td><img src="media/img/6x.jpg" border=0></td>
    </tr></table>
</body>
</html>

shop/templates/shop/7.html
<link rel="stylesheet" href="/static/reg.css" />
<!DOCTYPE html>
<html>
<head>
    <meta  charset="utf-8">
	<title></title>
<body>
    <h1>小芳超市（仓前店）路线<input type="button" class="a1" value="返回" onclick="javascript:history.back();"></h1>
    <table><tr>
        <td><img src="media/img/m7.jpg" border=0></td>
        <td><img src="media/img/7x.jpg" border=0></td>
    </tr></table>
</body>
</html>

shop/templates/shop/9.html
<link rel="stylesheet" href="/static/reg.css" />
<!DOCTYPE html>
<html>
<head>
    <meta  charset="utf-8">
	<title></title>
<body>
    <h1>杭州师范大学仓前新校区超市 路线<input type="button" class="a1" value="返回" onclick="javascript:history.back();"></h1>
    <table><tr>
        <td><img src="media/img/m9.jpg" border=0></td>
        <td><img src="media/img/9x.jpg" border=0></td>
    </tr></table>
</body>
</html>

shop/templates/shop/add1.html
<link rel="stylesheet" href="/static/reg.css" />
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% endblock %}
{% block content %}
    <title>添加商品</title>
<style>
</style>
    <div class="pg_body">
    <h2>添加商品</h2>
        <div class="menu">商品名:
        </div>
        <div class="kong">
            <input id="text1" type="text" name="name"><span id="div11" class="tian" style="margin-top: 4px"><span>
        </div>  
        <div class="menu">分类:
        </div>
        <div class="kong">
            <input id="i5" type="text" name="kind">
        </div>
        <div class="menu">上传商品图片:
        </div>
        <div class="kong">
            <input type="file" name="file" value="img" accept="image/*">
        </div> 
        <div class="menu">价格:
        </div>
        <div class="kong">
            <input id="text4" type="text" name="price">
            <span id="div4" class="tian"><span>
        </div>       
        <div class="menu">商品描述:
        </div>
        <div class="kong">
            <input name="meno" style="width: 200px;height: 100px;">
        </div>
    </div>
<div class="can">
    <hr>
            <input id="i111" type="submit" name="002" value="保 存">
            <input id="i222" type="submit" name="004" value="取 消" onclick="javascript:history.back();">
        </div>
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<link rel="stylesheet" href="/static/base.css" />
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <style>
   
</style>
</head>
<body>
      <div id="header">
      <img id="logo" src="/media/img/logo1.jpg" width="100" >
      <h1>杭州师范大学天猫超市店</h1>
      </div>
    <div class="user">
    <p><a style="float:left" href="{% url "shop:index" %}"><input style="text-align:left;" class="canot" type="submit" name="004" value="返 回"></a>
       {% if request.user.is_authenticated %}
        你好{{ request.user.first_name }},{{ request.user.username }},<a href="{% url 'logout' %}">退出</a>
            {% else %}
            <a href="{% url 'login' %}">登陆</a>
        {% endif %}</p>
    </div> <hr />
    <div id="content" >
        {% block content %}
        {% endblock %}
    </div>
    <br><br>
    <div id="footer">
     Copyright © UNTITLED
     </div>
</body>
</html>

shop/templates/shop/index.html
{% load static %}
    <link rel="stylesheet" href="/static/base.css" />
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <style>
</style>
<style>
*{ margin:0; padding:0; list-style:none;}
#box{ width:1000px; border:1px solid #000; height:160px; margin:30px auto; position:relative; overflow:hidden;}
#box ul{ position:absolute; left:0; top:0;}
#box ul li{ width:1000px; height:200px; float:left; padding:5px;}
</style>    
<script>    
window.onload=function(){    
    var oBox=document.getElementById('box');    
    var oUl=oBox.children[0];    
    var aLi=oUl.children;    
         
    <!--复制一份内容 ，制作出无缝的效果   -->
    oUl.innerHTML+=oUl.innerHTML;    
    oUl.style.width=aLi.length*aLi[0].offsetWidth+'px';    
         
    setInterval(function(){   <!--开定时器，这样就可以自己切换，无需人工干预。 -->
        var l=oUl.offsetLeft-10; <!-- 图片切换，就是移动距离-->
        if(l<=-oUl.offsetWidth/2){    
            l=0;    
        }    
        oUl.style.left=l+'px';    
    },150);    
};    
</script>    
</head>
<body>
 <div class = "pg_header">
        <!--<a class = "logo">LOGO</a>-->
        <img class="i1" src="media/img/logo.png"  />
        <a class="pg_dl" id="i77">超码超市管理系统</a>
    </div>
     
    <div class="user"style="TEXT-ALIGN: right">
     </a>
        <a href="{% url "shop:xxx" %}">我的位置</a>
        <a href="{% url "shop:product2_list" %}">我的超市</a>
        <a href="{% url "shop:market" %}">个人中心</a>
        {% if request.user.is_authenticated %}
        你好{{ request.user.first_name }},{{ request.user.username }},<a href="{% url 'logout' %}">退出</a>
            {% else %}
            <a href="{% url 'login' %}">登陆</a>
        {% endif %}
    </div> <hr />
<div id="box">    
    <ul>    
     <li><img src="media/img/1.jpg" width="1000"></li>    
       <li><img src="media/img/2.jpg" width="1000"></li>    
       <li><img src="media/img/3.jpg" width="1000"></li>    
       <li><img src="media/img/4.jpg" width="1000"></li>      
   </ul>    
</div>
    <div id="show" style="TEXT-ALIGN: center">
     <img src="media/img/a.jpg" width="250">
     <img src="media/img/b.jpg" width="250">
     <img src="media/img/c.jpg" width="250">
     <img src="media/img/d.jpg" width="250">
     </div>
    <div id="show2" style="TEXT-ALIGN: center">
     <img src="media/img/e.jpg" width="250">
     <img src="media/img/f.jpg" width="250">
     <img src="media/img/g.jpg" width="250">
     <img src="media/img/h.jpg" width="250">
     </div>
     <div id="shop">
           <div style="text-align: center;" class="sort">
           <form role="search" method="get" id="searchform" action="{% url 'shop:search' %}">
          {% csrf_token %}
          <input type="search" name="q" placeholder="Search" required>
          <button type="submit"><span class="ion-ios-search-strong"></span>搜索</button>
        </form>
     <a href="{{a.html}}">综合排序</a>
     <a href="{{b.html}}">距离最近</a>
     <a href="{{c.html}}">买过的店</a>
     </div>
     <br>
     {% if not category %}{% endif %}
                <a href="{% url "shop:product_list" %}">
     <img src="media/img/s5.png" width="482">
     </a>
     <img src="media/img/s6.png" width="482">
     <br>
     <img src="media/img/s7.png" width="482">
     <img src="media/img/s8.png" width="482">
     <br>
     <img src="media/img/s11.png" width="482">
     <img src="media/img/s12.png" width="482">
     <br>
     <img src="media/img/s13.png" width="482">
     <img src="media/img/s14.png" width="482">
     <br>
     <img src="media/img/s15.png" width="482">
     <img src="media/img/s16.png" width="482">
     </div>
 <br><br>
    <div id="footer">
     Copyright © UNTITLED
     </div>
</body>
</html>

shop/templates/shop/market.html
{%load static%}
<link rel="stylesheet" href="/static/reg.css" />
<!DOCTYPE html>
<head>
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <style>
    </style>
    <script>
   function clicka1(){
        document.getElementById("div22").style.display = "none";//隐藏
        document.getElementById("div33").style.display = "none";//隐藏
        document.getElementById("div11").style.display = "block";//显示
    }
    function clicka2(){
        document.getElementById("div11").style.display = "none";//隐藏
        document.getElementById("div33").style.display = "none";//隐藏
        document.getElementById("div22").style.display = "block";//显示
    }
    function clicka3(){
        document.getElementById("div11").style.display = "none";//隐藏
        document.getElementById("div22").style.display = "none";//隐藏
        document.getElementById("div33").style.display = "block";//显示
    }
    </script>
</head>
<body>
    <div class="pg_header">
        <!--<img class="i1" src="{%static "/sign.jpg"%}" style="margin-left:-6%"  width="111" height="111" />-->
        <img class="hh1" src="media/img/logo.png"  />
         <a class="pg_dl" id="i78" href="http://127.0.0.1:8000/login">首页</a>
    </div>
    <div class="bodyy">
        <div class ="bo3" >
            <h3>个人中心</h3>
            <li><a class="aa" onclick="clicka1()">我的资料</a></li>
            <br>
            <li><a class="aa" onclick="clicka2()">我的超市</a></li>
            <br>
            <li><a class="aa" onclick="clicka3()">活动信息</a></li>
        </div>
        <div class="div1" id="div11">
        <br><br><br> <br>
            <div class="pg_body">
            
                <div class="menu">用户名:
                </div>
                <div class="kong">
                    <input id="text1" type="text" name="username" value={{i.username}}><span id="div11" class="tian" style="margin-top: 4px"><span>
                </div>  
                <div class="menu">性别:
                </div>
                <div class="kong" style="width:200px;">
                {% if i.gender == 'M' %}
                    男<input type="radio" name="sex" value="1" checked>
                    女 <input type="radio" name="sex" value="2">
                {% else %}
                    男<input type="radio" name="sex" value="1">
                    女 <input type="radio" name="sex" value="2" checked>
                {% endif %}
                </div>
                <div class="menu">电话号码:
                </div>
                <div class="kong">
                    <input id="i5" type="text" name="phonenumber" value={{i.phonenumber}}>
                </div>
                <div class="menu">邮箱地址:
                </div>
                <div class="kong">
                    <input id="text4" type="text" name="01" value={{i.email}}>
                    <span id="div4" class="tian"><span>
                </div>
                <div class="menu">头像:    
                </div>
                <div class="kong">
                    <input type="file" name="file" value="选择头像" accept="image/*">
                </div>        
                <div class="menu">个人签名:
                </div>
                <div class="kong">
                    <input name="meno" style="width: 280px;height: 40px;" value={{i.signature}}>
                    </input>
                </div>
                <div class="can">
                    <hr>
                    <input id="i111" type="submit" name="002" value="保 存">
                     <p style="width: 100px;display: inline-block;"></p>
                    <input id="i222" type="submit" name="004" value="返 回" onclick="javascript:history.back();">
                </div>
            </div>
        </div>
        <div class="div2" id="div22" style="display: none;">
        <br><br><br> <br><br><br>
            <div class="pg_body">
                <div class="menu">超市名:
                </div>
                <div class="kong">
                    <input id="text1" type="text" name="username" value={{j.marketname}}><span id="div12" class="tian" style="margin-top: 4px"><span>
                </div>
                <div class="menu">超市图片: 
                </div>
                <div class="kong">
                    <br>
                    <input type="file" name="file" value="选择头像" accept="image/*">
                </div> 
                <div class="can">
                    <input id="i111" type="submit" name="002" value="保 存">
                                         <p style="width: 100px;display: inline-block;"></p>
                    <input id="i222" type="submit" name="004" value="返 回" onclick="javascript:history.back();">
                </div>       
            </div>
        </div>
        <div class="div3" id="div33" style="display: none;">
        <br><br><br> <br><br><br>
            <div class="pg_body">
                <div class="menu">活动信息:
                </div>
                <div class="kong">
                    <input id="text1" type="text" name="username" value={{j.activityTXT}}><span id="div13" class="tian" style="margin-top: 4px"><span>
                </div>
                <br><br><br><br>
                <div class="menu">
                <div class="kong"><input type="file" name="file" value="选择文件" accept="image/*"></div>
                <br>
                折扣信息:
                </div>
                <div class="kong">
                    <input id="text1" type="text" name="username" value={{j.countTXT}}><span id="div13" class="tian" style="margin-top: 4px"><span>
                </div>
                <br><br><br><br><br>
                <div class="kong"><input type="file" name="file" value="选择文件" accept="image/*"></div>
                <div class="can">
                    <input id="i111" type="submit" name="002" value="保 存">
                                         <p style="width: 100px;display: inline-block;"></p>
                    <input id="i222" type="submit" name="004" value="返 回" onclick="javascript:history.back();">
                </div>
            </div>
        </div>
    </div>
</body>
</html>

shop/templates/shop/xxx.html
<link rel="stylesheet" href="/static/reg.css" />
<!DOCTYPE html>
<html>
<head>
    <meta  charset="utf-8">
	<title></title>
<body>
    <h1>附近超市<input type="button" class="a1" value="返回" onclick="javascript:history.back();"></h1>
    <center><img style="float:left" src='/media/img/aa.jpg' height="500" width="1000"/></center>
    <h2>超市名称</h2>
    <h3>1 联华超市（杭州大华店）<a href="{% url "shop:1" %}"><input type="button" value="去这里"></a><br>
   2 乐时城<a href="{% url "shop:2" %}"><input type="button" value="去这里"></a><br>
    3 世纪华联（永福店）<a href="{% url "shop:3" %}"><input type="button" value="去这里"></a><br>
    4 通城好又多购物（梦想小镇店）<a href="{% url "shop:4" %}"><input type="button" value="去这里"></a><br>
    5 好又多超市（五常永福店）<a href="{% url "shop:5" %}"><input type="button" value="去这里"></a><br>
    6 华联超市（仓前店）<a href="{% url "shop:6" %}"><input type="button" value="去这里"></a><br>
    7 小芳超市（仓前店）<a href="{% url "shop:7" %}"><input type="button" value="去这里"></a> <br>
    8 好又多（仓前店）<a href="{% url "shop:8" %}"><input type="button" value="去这里"></a><br>
    9 杭州师范大学仓前新校区超市 <a href="{% url "shop:9" %}"><input type="button" value="去这里"></a><br>
    10 如海仓前购物中心 <a href="{% url "shop:10" %}"><input type="button" value="去这里"></a></h3><br>

    </div>
</body>
</html>